version: '3'
services:
  web:
    build: .
    image: halvong/stripe_rails_web
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stripe_rails
    volumes:
      - .:/usr/src/app
    #env_file:
    #  - .env/development/database
    #  - .env/development/web
  database:
    image: postgres
    ports:
      - "32772:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stripe_rails
    #env_file:
    #  - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/stripe_data
volumes:
  db_data: